@echo off
color 0a

cls 
echo.
echo Setup Stick, please wait.....
adb shell settings put secure install_non_market_apps 1
adb shell settings put global adb_enabled 1
adb shell settings put global setup_wizard_has_run 1
adb shell settings put secure user_setup_complete 1
adb shell settings put global device_provisioned 1
echo Allow root
adb shell su -c "ls /sdcard/" 
pause
echo remove Bloatware
echo Please Wait, removal running...............
adb shell "su -c pm disable com.amazon.kindle.cms"
adb shell "su -c pm disable com.amazon.tv.launcher"
adb shell "su -c pm disable com.amazon.tv.oobe"
adb shell "su -c pm disable com.amazon.device.sale.service"
adb shell "su -c pm disable com.amazon.recess"
adb shell "su -c pm disable com.amazon.whisperplay.contracts"
adb shell "su -c pm disable com.amazon.bueller.photos"
adb shell "su -c pm disable com.amazon.device.sync"
adb shell "su -c pm disable com.amazon.webview"
adb shell "su -c pm disable com.amazon.tv.csapp"
adb shell "su -c pm disable com.amazon.tcomm.client"
adb shell "su -c pm disable com.amazon.client.metrics"
adb shell "su -c pm disable amazon.jackson19"
adb shell "su -c pm disable com.amazon.device.software.ota"
adb shell "su -c pm disable com.amazon.ags.app"
adb shell "su -c pm disable com.amazon.application.compatibility.enforcer"
adb shell "su -c pm disable com.amazon.whisperplay.service.install"
adb shell "su -c pm disable com.amazon.device.software.ota.override"
adb shell "su -c pm disable com.amazon.communication.discovery"
adb shell "su -c pm disable com.amazon.device.sync.sdk.internal"
adb shell "su -c pm disable com.amazon.bueller.music"
adb shell "su -c pm disable com.amazon.application.compatibility.enforcer.sdk.library"
adb shell "su -c pm disable com.amazon.vizzini"
adb shell "su -c pm disable com.amazon.tv.forcedotaupdater.v2"
adb shell "su -c pm disable com.amazon.avod"
adb shell "su -c pm disable com.amazon.shoptv.client"
adb shell "su -c pm disable android.amazon.perm"
adb shell "su -c pm disable com.amazon.android.marketplace"
adb shell "su -c pm disable com.amazon.awvflingreceiver"
adb shell "su -c pm disable com.amazon.bueller.notification"
adb shell "su -c pm disable com.amazon.device.crashmanager"
adb shell "su -c pm disable com.amazon.device.messaging"
adb shell "su -c pm disable com.amazon.device.messaging.sdk.internal.library"
adb shell "su -c pm disable com.amazon.device.messaging.sdk.library"
adb shell "su -c pm disable com.amazon.kso.blackbird"
adb shell "su -c pm disable com.amazon.ods.kindleconnect"
adb shell "su -c pm disable com.amazon.providers"
adb shell "su -c pm disable com.amazon.providers.contentsupport"
adb shell "su -c pm disable com.amazon.securitysyncclient"
adb shell "su -c pm disable com.amazon.sharingservice.android.client.proxy"
adb shell "su -c pm disable com.amazon.sync.provider.ipc"
adb shell "su -c pm disable com.amazon.sync.service"
adb shell "su -c pm disable com.amazon.tv.legal.notices"
adb shell "su -c pm disable com.amazon.tv.support"
adb shell "su -c pm disable com.amazon.platform.fdrw"
adb shell "su -c pm disable com.android.managedprovisioning"
adb shell "su -c pm disable com.amazon.device.bluetoothdfu"
adb shell "su -c pm disable com.amazon.tv.fw.metrics"
adb shell "su -c pm disable com.amazon.device.logmanager"
adb shell "su -c pm disable com.amazon.dcp"
adb shell "su -c pm disable com.amazon.dcp.contracts.framework.library"
adb shell "su -c pm disable com.amazon.android.service.networkmonitor"
adb shell "su -c pm disable com.amazon.tmm.tutorial"
adb shell "su -c pm disable com.amazon.logan"
adb shell "su -c pm disable com.amazon.tv.nimh"
adb shell "su -c pm disable com.ivona.tts.oem"
adb shell "su -c pm disable com.ivona.orchestrator"
adb shell "su -c pm disable com.amazon.alexashopping"
adb shell "su -c pm disable com.amazon.ftv.glorialist"
adb shell "su -c pm disable com.amazon.tv.livetv"
adb shell "su -c pm disable com.amazon.wifilocker"
adb shell "su -c pm disable com.amazon.ssdpservice"
adb shell "su -c pm disable com.amazon.alta.h2clientservice"
adb shell "su -c pm disable com.amazon.dialservice"
adb shell "su -c pm disable com.amazon.cardinal"
adb shell "su -c pm disable com.amazon.tifobserver"
adb shell "su -c pm disable com.amazon.aca"
adb shell "su -c pm disable com.amazon.aria"
adb shell "su -c pm disable com.amazon.firehomestarter"
adb shell "su -c pm disable com.amazon.franktvinput"
adb shell "su -c pm disable com.amazon.hedwig"
adb shell "su -c pm disable com.amazon.naatyam"
adb shell "su -c pm disable com.amazon.alexa.externalmediaplayer.fireos"
adb shell "su -c pm disable com.amazon.ale"
adb shell "su -c pm disable com.amazon.avl.ftv"
adb shell "su -c pm disable com.amazon.ceviche"
adb shell "su -c pm disable com.amazon.dpcclient"
adb shell "su -c pm disable com.amazon.firebat"
adb shell "su -c pm disable com.amazon.firerestapiframework"
adb shell "su -c pm disable com.amazon.katoch"
adb shell "su -c pm disable com.amazon.tv.releasenotes"
adb shell "su -c pm disable com.amazon.tv.routing"
adb shell "su -c pm disable com.amazon.tahoe"
adb shell "su -c pm disable com.amazon.whisperjoin.middleware.np"
adb shell "su -c pm disable com.amznfuse.operatorredirection"
echo reboot recovery
adb shell reboot recovery
wait 35
adb shell "mount -o rw /system"
adb push "bootanimation.zip" /sdcard/bootanimation.zip
adb shell "mv /system/media/bootanimation.zip /system/media/bootanimation.old"
adb shell "rm /system/media/bootanimation.zip"
adb shell "cp /sdcard/bootanimation.zip /system/media/bootanimation.zip"
adb shell "chmod 644 /system/media/bootanimation.zip"
echo Debloating Amazon Apps...
wait.exe 3
:: FireOS 5.05 and Higher
adb shell "rm -r /system/priv-app/com.amazon.avod/"
adb shell "rm -r /system/priv-app/com.amazon.shoptv.client/"
adb shell "rm -r /system/priv-app/android.amazon.perm/"
adb shell "rm -r /system/priv-app/com.amazon.ags.app/"
adb shell "rm -r /system/priv-app/com.amazon.android.marketplace/"
adb shell "rm -r /system/priv-app/com.amazon.awvflingreceiver/"
adb shell "rm -r /system/priv-app/com.amazon.bueller.music/"
adb shell "rm -r /system/priv-app/com.amazon.bueller.notification/"
adb shell "rm -r /system/priv-app/com.amazon.device.crashmanager/"
adb shell "rm -r /system/priv-app/com.amazon.device.messaging/"
adb shell "rm -r /system/priv-app/com.amazon.device.messaging.sdk.internal.library/"
adb shell "rm -r /system/priv-app/com.amazon.device.messaging.sdk.library/"
adb shell "rm -r /system/priv-app/com.amazon.device.sync/"
adb shell "rm -r /system/priv-app/com.amazon.device.sync.sdk.internal/"
adb shell "rm -r /system/priv-app/com.amazon.kindle.cms/"
adb shell "rm -r /system/priv-app/com.amazon.kso.blackbird/"
adb shell "rm -r /system/priv-app/com.amazon.ods.kindleconnect/"
adb shell "rm -r /system/priv-app/com.amazon.providers/"
adb shell "rm -r /system/priv-app/com.amazon.providers.contentsupport/"
adb shell "rm -r /system/priv-app/com.amazon.recess/"
adb shell "rm -r /system/priv-app/com.amazon.securitysyncclient/"
adb shell "rm -r /system/priv-app/com.amazon.sharingservice.android.client.proxy/"
adb shell "rm -r /system/priv-app/com.amazon.sync.provider.ipc/"
adb shell "rm -r /system/priv-app/com.amazon.sync.service/"
adb shell "rm -r /system/priv-app/com.amazon.tv.legal.notices/"
adb shell "rm -r /system/priv-app/com.amazon.tv.support/"
adb shell "rm -r /system/priv-app/com.amazon.webview/"
adb shell "rm -r /system/priv-app/com.amazon.platform.fdrw/"
adb shell "rm -r /system/priv-app/com.android.managedprovisioning/"
adb shell "rm -r /system/priv-app/com.amazon.device.bluetoothdfu/"
adb shell "rm -r /system/priv-app/com.amazon.tv.fw.metrics/"
adb shell "rm -r /system/priv-app/com.amazon.device.logmanager/"
adb shell "rm -r /system/priv-app/com.amazon.dcp/"
adb shell "rm -r /system/priv-app/com.amazon.dcp.contracts.framework.library/"
adb shell "rm -r /system/priv-app/com.amazon.device.software.ota/"
adb shell "rm -r /system/priv-app/com.amazon.device.software.ota.override/"
adb shell "rm -r /system/priv-app/com.amazon.android.service.networkmonitor/"
adb shell "rm -r /system/priv-app/com.amazon.tmm.tutorial/"
adb shell "rm -r /system/priv-app/com.amazon.tv.csapp/"
adb shell "rm -r /system/priv-app/com.amazon.bueller.photos/"
adb shell "rm -r /system/priv-app/com.amazon.vizzini/"
adb shell "rm -r /system/priv-app/com.amazon.logan/"
adb shell "rm -r /system/priv-app/com.amazon.tv.nimh/"
adb shell "rm -r /system/priv-app/com.ivona.tts.oem/"
adb shell "rm -r /system/priv-app/com.ivona.orchestrator/"
adb shell "rm -r /system/priv-app/com.amazon.device.sale.service/"
adb shell "rm -r /system/priv-app/com.amazon.alexashopping/"
adb shell "rm -r /system/priv-app/com.amazon.ftv.glorialist/"
adb shell "rm -r /system/priv-app/com.amazon.tv.livetv/"
adb shell "rm -r /system/priv-app/com.amazon.wifilocker/"
adb shell "rm -r /system/priv-app/com.amazon.ssdpservice/"
adb shell "rm -r /system/priv-app/com.amazon.alta.h2clientservice/"
adb shell "rm -r /system/priv-app/com.amazon.dialservice/"
adb shell "rm -r /system/priv-app/com.amazon.cardinal/"
adb shell "rm -r /system/priv-app/com.amazon.tifobserver/"
adb shell "rm -r /system/priv-app/com.amazon.aca/"
adb shell "rm -r /system/priv-app/com.amazon.aria/"
adb shell "rm -r /system/priv-app/com.amazon.franktvinput/"
adb shell "rm -r /system/priv-app/com.amazon.hedwig/"
adb shell "rm -r /system/priv-app/com.amazon.naatyam/"
adb shell "rm -r /system/priv-app/com.amazon.alexa.externalmediaplayer.fireos/"
adb shell "rm -r /system/priv-app/com.amazon.ale/"
adb shell "rm -r /system/priv-app/com.amazon.avl.ftv/"
adb shell "rm -r /system/priv-app/com.amazon.ceviche/"
adb shell "rm -r /system/priv-app/com.amazon.dpcclient/"
adb shell "rm -r /system/priv-app/com.amazon.firebat/"
adb shell "rm -r /system/priv-app/com.amazon.firerestapiframework/"
adb shell "rm -r /system/priv-app/com.amazon.katoch/"
adb shell "rm -r /system/priv-app/com.amazon.tv.releasenotes/"
adb shell "rm -r /system/priv-app/com.amazon.tv.routing/"
adb shell "rm -r /system/priv-app/com.amazon.tahoe/"
adb shell "rm -r /system/priv-app/com.amazon.whisperjoin.middleware.np/"
adb shell "rm -r /system/priv-app/com.amznfuse.operatorredirection/"
adb shell "rm -r /system/priv-app/com.amazon.imdb.tv.android.app/"
wait.exe 5
echo Removing any added System Components from Amazon App Updates...
adb shell "rm -r /data/app/com.amazon.aca-1/"
adb shell "rm -r /data/app/com.amazon.ags.app-1/"
adb shell "rm -r /data/app/com.amazon.alexashopping-1/"
adb shell "rm -r /data/app/com.amazon.amazonvideo.livingroom.firetv-1/"
adb shell "rm -r /data/app/com.amazon.appaccesskeyprovider-1/"
adb shell "rm -r /data/app/com.amazon.aria-1/"
adb shell "rm -r /data/app/com.amazon.avl.ftv-1/"
adb shell "rm -r /data/app/com.amazon.avod-1/"
adb shell "rm -r /data/app/com.amazon.bueller.music-1/"
adb shell "rm -r /data/app/com.amazon.cardinal-1/"
adb shell "rm -r /data/app/com.amazon.firebat-1/"
adb shell "rm -r /data/app/com.amazon.ftv.glorialist-1/"
adb shell "rm -r /data/app/com.amazon.hedwig-1/"
adb shell "rm -r /data/app/com.amazon.katoch-1/"
adb shell "rm -r /data/app/com.amazon.kso.blackbird-1/"
adb shell "rm -r /data/app/com.amazon.shoptv.client-1/"
adb shell "rm -r /data/app/com.amazon.tahoe-1/"
adb shell "rm -r /data/app/com.amazon.tv.launcher-1/"
adb shell "rm -r /data/app/com.amazon.tv.livetv-1/"
adb shell "rm -r /data/app/com.amazon.tv.ottssocompanionapp-1/"
adb shell "rm -r /data/app/com.amazon.tv.releasenotes-1/"
adb shell "rm -r /data/app/com.amazon.aca-2/"
adb shell "rm -r /data/app/com.amazon.ags.app-2/"
adb shell "rm -r /data/app/com.amazon.alexashopping-2/"
adb shell "rm -r /data/app/com.amazon.amazonvideo.livingroom.firetv-2/"
adb shell "rm -r /data/app/com.amazon.appaccesskeyprovider-2/"
adb shell "rm -r /data/app/com.amazon.aria-2/"
adb shell "rm -r /data/app/com.amazon.avl.ftv-2/"
adb shell "rm -r /data/app/com.amazon.avod-2/"
adb shell "rm -r /data/app/com.amazon.bueller.music-2/"
adb shell "rm -r /data/app/com.amazon.cardinal-2/"
adb shell "rm -r /data/app/com.amazon.firebat-2/"
adb shell "rm -r /data/app/com.amazon.ftv.glorialist-2/"
adb shell "rm -r /data/app/com.amazon.hedwig-2/"
adb shell "rm -r /data/app/com.amazon.katoch-2/"
adb shell "rm -r /data/app/com.amazon.kso.blackbird-2/"
adb shell "rm -r /data/app/com.amazon.shoptv.client-2/"
adb shell "rm -r /data/app/com.amazon.tahoe-2/"
adb shell "rm -r /data/app/com.amazon.tv.launcher-2/"
adb shell "rm -r /data/app/com.amazon.tv.livetv-2/"
adb shell "rm -r /data/app/com.amazon.tv.ottssocompanionapp-2/"
adb shell "rm -r /data/app/com.amazon.tv.releasenotes-2/"
adb shell "rm -r /data/app/com.amazon.imdb.tv.android.app*/"
adb shell "mv /etc/security/otacerts.zip /etc/security/old.otacerts.zip.old"
adb shell "rm -r /system/media/alarms/"
adb shell "rm -r /system/media/notifications/"
adb shell "rm -r /system/media/ringtones/"
 
wait 2
echo Remove Amazon Launcher...
adb push Markus-TWRP.zip /sdcard/Markus-TWRP.zip
adb shell twrp install /sdcard/Markus-TWRP.zip
echo Re-Installing BusyBox...
adb push Busybox.zip /sdcard/Busybox.zip
adb shell twrp install /sdcard/Busybox.zip
echo Wiping Cache and Dalvik Cache...
adb shell twrp wipe cache
wait 5
adb shell twrp wipe dalvik
echo Re-Installing Magisk for SU Access...
adb.exe push Magisk-v20.4.zip /sdcard/Magisk-v20.4.zip
adb shell twrp install /sdcard/Magisk-v20.4.zip
echo Fixing Permissions...
adb shell "chown -R media_rw:media_rw /data/media/"
adb shell "find /data/media/ -type d -exec chmod 775 {} ';'"
adb shell "find /data/media/ -type f -exec chmod 664 {} ';'"
adb shell "restorecon -FR /data/media/"
echo Reboot...
echo Please Wait
adb.exe reboot
echo Done!